# .github/workflows/cypress-tests.yml
name: Cypress Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run Cypress test
        run: npx cypress run --spec "root/cypress/e2e/spec.cy.js"
